version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: landd_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=landd_db
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
