# Generated by Django 4.2.13 on 2025-05-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='category',
            field=models.CharField(choices=[('north', 'ภาคเหนือ'), ('central', 'ภาคกลาง'), ('northeast', 'ภาคตะวันออกเฉียงเหนือ'), ('east', 'ภาคตะวันออก'), ('west', 'ภาคตะวันตก'), ('south', 'ภาคใต้')], max_length=20),
        ),
    ]
