# Generated by Django 4.2.13 on 2025-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('north', 'ภาคเหนือ'), ('central', 'ภาคกลาง'), ('northeast', 'ภาคตะวันออกเฉียงเหนือ'), ('east', 'ภาคตะวันออก'), ('west', 'ภาคตะวันตก'), ('south', 'ภาคใต้')], max_length=50),
        ),
    ]
