# Generated by Django 4.2.13 on 2025-05-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_alter_land_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.category'),
        ),
    ]
