# Generated by Django 5.2 on 2025-05-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_alter_land_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
