# Generated by Django 5.2 on 2025-05-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_alter_category_options'),
        ('product_management', '0003_alter_land_category'),
    ]

    operations = [
    ]
