# Generated by Django 4.2.13 on 2025-05-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_alter_land_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ภาคเหนือ', 'North'), ('ภาคกลาง', 'Central'), ('ภาคตะวันตก', 'West'), ('ภาคตะวันออก', 'East'), ('ภาคใต้', 'South'), ('ภาคตะวันออกเฉียงเหนือ', 'Northeast')], max_length=50),
        ),
    ]
