# Generated by Django 4.2.13 on 2025-05-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ภาคเหนือ', 'ภาคเหนือ'), ('ภาคกลาง', 'ภาคกลาง'), ('ภาคตะวันออกเฉียงเหนือ', 'ภาคตะวันออกเฉียงเหนือ'), ('ภาคตะวันออก', 'ภาคตะวันออก'), ('ภาคตะวันตก', 'ภาคตะวันตก'), ('ภาคใต้', 'ภาคใต้')], max_length=50),
        ),
    ]
