# Generated by Django 5.2 on 2025-05-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_merge_20250505_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('north', 'ภาคเหนือ'), ('central', 'ภาคกลาง'), ('northeast', 'ภาคตะวันออกเฉียงเหนือ'), ('east', 'ภาคตะวันออก'), ('west', 'ภาคตะวันตก'), ('south', 'ภาคใต้')], max_length=50),
        ),
    ]
