# Generated by Django 5.0.4 on 2025-05-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='method_name',
            field=models.CharField(choices=[('pickup', 'รับโฉนดที่สำนักงาน'), ('appointment', 'นัดรับโฉนด')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_name',
            field=models.CharField(choices=[('banking', 'Mobile Banking'), ('credit', 'Credit Card')], max_length=50),
        ),
    ]
